steps:
- name: gcr.io/cloud-builders/go:wheezy
  args: [
    'build',
    '-o', 'debgetter-darwin',
    'github.com/GoogleCloudPlatform/distroless/packages/deb_pkg',
  ]
  env: ['GOOS=linux']
- name: gcr.io/cloud-builders/go:wheezy
  args: [
    'build',
    '-o', 'debgetter-linux',
    'github.com/GoogleCloudPlatform/distroless/packages/deb_pkg'
  ]
  env: ['GOOS=darwin']
- name: gcr.io/cloud-builders/go:wheezy
  args: [
    'build',
    '-o', 'debgetter-windows',
    'github.com/GoogleCloudPlatform/distroless/packages/deb_pkg',
  ]
  env: ['GOOS=windows']
- name: gcr.io/cloud-builders/gsutil
  args: [
    'cp', '-r',
    'debgetter-*',
    'gs://$PROJECT_ID/'
  ]
